spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/social_media_db
    username: postgres
    password: your_password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379


server:
  port: ${PORT:8080}